version: "3.3"

services:
 db:
    image: postgres:10.6
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

 shortenservice:
  build: shorten-ws/.
  image: shorten-ws:0.0.1
  ports:
   - "8080:8080"
  depends_on:
      - db
  networks:
      - webnet
  restart: on-failure
  deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  
networks:
  webnet: